local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: odom
      robot_base_frame: base_link
      rolling_window: true
      width: 4
      height: 4
      resolution: 0.05
      plugins: ["obstacle_layer", "inflation_layer"]

      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: depth_cloud people_cloud

        depth_cloud:
          topic: /camera/depth/color/points   # 사용 중인 포인트클라우드 토픽으로 맞추세요
          data_type: "PointCloud2"
          expected_update_rate: 5.0
          marking: True
          clearing: True
          min_obstacle_height: 0.05
          max_obstacle_height: 2.0
          obstacle_max_range: 3.0
          raytrace_max_range: 4.0
          inf_is_valid: False

        people_cloud:
          topic: /people_obstacles
          data_type: "PointCloud2"
          expected_update_rate: 10.0
          observation_persistence: 0.5   # YOLO 드랍 보정
          marking: True
          clearing: False
          min_obstacle_height: 0.05
          max_obstacle_height: 2.2

      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.6
        cost_scaling_factor: 5.0
